### ISSUE TITLE
flutter build windows command failed："goreleaser: error: unexpected bash"

### ISSUE THREAD

**Issue by AlienwareHe** [go-flutter-desktop/go-flutter#339]
Thanks~
when i use flutter build command on macos, the result is failed,but flutter build darwin-pkg command is normal.    
error details:
```
$hover build windows
hover: Using engine from cache
hover: Cleaning the build directory
hover: Bundling flutter app
hover: Because darwin is not able to compile for windows out of the box, a cross-compiling container is used
Sending build context to Docker daemon  2.048kB
Step 1/2 : FROM goreng/golang-cross
 ---> fd603bc6970e
Step 2/2 : RUN apt-get update && apt-get install libgl1-mesa-dev xorg-dev -y
 ---> Using cache
 ---> 0b5f59336c8e
Successfully built 0b5f59336c8e
Successfully tagged hover-build-cc:latest
hover: Cross-Compiling 'go-flutter' and plugins using docker
can not find any private key, ignore...

goreleaser: error: unexpected bash, try --help
```

**Comment by jld3103** [comment]
This is already fixed. Please upgrade hover (`go get -u github.com/go-flutter-desktop/hover`) and remove the `go/cross-compiling` dir (`rm -rf go/cross-compiling`). Please let me know if it worked for you.

**Comment by AlienwareHe** [comment]
sorry~ it looks like does not work,my hover version looks like is the newst:
```
alienhe@alienware-2:~/go/src/github.com/go-flutter-desktop/hover$ls -l
total 64
-rw-r--r--   1 alienhe  staff  1518 Dec 26 21:59 LICENSE
-rw-r--r--   1 alienhe  staff  5177 Dec 26 21:59 README.md
drwxr-xr-x   5 alienhe  staff   160 Dec 26 21:59 assets
drwxr-xr-x  14 alienhe  staff   448 Jan 12 18:22 cmd
-rw-r--r--   1 alienhe  staff   661 Jan 12 18:22 go.mod
-rw-r--r--   1 alienhe  staff  6786 Jan 12 18:22 go.sum
drwxr-xr-x  10 alienhe  staff   320 Dec 26 21:59 internal
-rw-r--r--   1 alienhe  staff   100 Dec 26 21:59 main.go
-rw-r--r--   1 alienhe  staff   326 Dec 26 21:59 renovate.json
```
but when i rm -rf go/cross-compiling it also error:
```
alienhe@alienware-2:~/code/flutter/excel_tools$rm -rf go/cross-compiling/
alienhe@alienware-2:~/code/flutter/excel_tools$hover build windows
hover: Using engine from cache
hover: Cleaning the build directory
hover: Bundling flutter app
hover: Because darwin is not able to compile for windows out of the box, a cross-compiling container is used
hover: A Dockerfile for cross-compiling for windows has been created at go/cross-compiling/windows. You can add it to git.
Sending build context to Docker daemon  2.048kB
Step 1/2 : FROM goreng/golang-cross
 ---> fd603bc6970e
Step 2/2 : RUN apt-get update && apt-get install libgl1-mesa-dev xorg-dev -y
 ---> Using cache
 ---> 0b5f59336c8e
Successfully built 0b5f59336c8e
Successfully tagged hover-build-cc:latest
hover: Cross-Compiling 'go-flutter' and plugins using docker
can not find any private key, ignore...
goreleaser: error: unexpected bash, try --help

```
Thanks~

**Comment by jld3103** [comment]
Can you do a `hover doctor` in your project?

**Comment by AlienwareHe** [comment]
$hover doctor
hover: Running on darwin
hover: Docker installed: true
hover: Sharing flutter version
Flutter 1.12.13+hotfix.6 • channel beta • git@github.com:flutter/flutter.git
Framework • revision 18cd7a3601 (5 weeks ago) • 2019-12-11 06:35:39 -0800
Engine • revision 2994f7e1e6
Tools • Dart 2.7.0
hover: Flutter engine commit: https://github.com/flutter/engine/commit/2994f7e1e6
hover: Finding out the C compiler version
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.2.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
hover: Sharing the content of go.mod
module excel_tools/go

go 1.13

require (
        github.com/AlienwareHe/flutter_file_picker/go v0.0.3
        github.com/go-flutter-desktop/go-flutter v0.34.0
        github.com/pkg/errors v0.8.1
)
hover: Sharing the content of hover.yaml
target: lib/main_desktop.dart
branch: ""
cache-path: ""
opengl: ""
docker: false
hover: Sharing the content of go/cmd
go/cmd/main.go  go/cmd/options.go

**Comment by AlienwareHe** [comment]
I try to rm the docker images and rerun 'hover build windows', but still the same error, and do I need to update go-flutter version with command "hover bumpversion";    
or are there has some other ways to sovle it.
Thanks~

**Comment by AlienwareHe** [comment]
I resolve it! I execute the command `go install github.com/go-flutter-desktop/hover` to re-generate the hover bin，then i remove the go/cross-compiling dir , then i success~
Thanks~
